import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { getDocsContent } from "@/lib/docs";
import { Book } from "lucide-react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SUNA Documentation",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const allDocs = getDocsContent();
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex min-h-screen">
          <aside className="w-64 bg-gray-50 border-r p-4">
            <h1 className="text-2xl font-bold mb-4">
              <Link href="/">SUNA Docs</Link>
            </h1>
            <nav>
              <ul>
                {allDocs.map((doc) => (
                  <li key={doc.id} className="mb-2">
                    <Link href={`/docs/${doc.id}`} className="flex items-center text-gray-700 hover:text-black">
                      <Book className="w-4 h-4 mr-2" />
                      {doc.title}
                    </Link>
                  </li>
                ))}
              </ul>
            </nav>
          </aside>
          <main className="flex-1 p-8">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
} 